name: Release

# Run workflow on commits to the `master` branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Deploy
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.BLOG_GH_TOKEN }}
